import { defineBackgroundSettings } from '@/domain/backgrounds/settingsDefinition';
import type { ParticleSettings } from '@/types/background';

/** Editable, persisted and runtime-safe settings for the particle scene. */
export const particleSettingsDefinition = defineBackgroundSettings<ParticleSettings>({
  pointSize: {
    group: 'appearance',
    label: 'Particle size',
    description: 'Rendered size of each particle.',
    defaultValue: 1.35,
    recommended: { min: 0.5, max: 3, step: 0.05 },
    runtime: { min: 0.05, max: 12 },
  },
  opacity: {
    group: 'appearance',
    label: 'Particle opacity',
    description: 'Maximum visibility of the particle field.',
    defaultValue: 0.32,
    recommended: { min: 0.1, max: 0.8, step: 0.02 },
    runtime: { min: 0, max: 2 },
  },
  idleStrength: {
    group: 'appearance',
    label: 'Idle movement',
    description: 'Strength of ambient movement while the scene is idle.',
    defaultValue: 1,
    recommended: { min: 0, max: 2, step: 0.05 },
    runtime: { min: 0, max: 5 },
  },
  noiseSpeed: {
    group: 'appearance',
    label: 'Flow speed',
    description: 'Speed of the procedural particle flow.',
    defaultValue: 0.075,
    recommended: { min: 0, max: 0.2, step: 0.005 },
    runtime: { min: 0, max: 1 },
  },
  pixelRatioCap: {
    group: 'appearance',
    label: 'Pixel-ratio cap',
    description: 'Maximum render resolution; lower values improve GPU performance.',
    defaultValue: 1.5,
    recommended: { min: 1, max: 2, step: 0.25 },
    runtime: { min: 0.5, max: 3 },
    presetValues: { high: 1.5, medium: 1.25, low: 1 },
  },
  interactionRadius: {
    group: 'interaction',
    label: 'Interaction radius',
    description: 'Area around the pointer that affects particles.',
    defaultValue: 0.24,
    recommended: { min: 0.1, max: 0.5, step: 0.01 },
    runtime: { min: 0.01, max: 2 },
  },
  repulsionStrength: {
    group: 'interaction',
    label: 'Repulsion strength',
    description: 'Force applied by pointer movement.',
    defaultValue: 3.45,
    recommended: { min: 1, max: 7, step: 0.05 },
    runtime: { min: 0, max: 30 },
  },
  vortexStrength: {
    group: 'interaction',
    label: 'Vortex strength',
    description: 'Rotational force transferred from pointer movement.',
    defaultValue: 0.66,
    recommended: { min: 0, max: 2, step: 0.01 },
    runtime: { min: 0, max: 10 },
  },
  clickStrength: {
    group: 'interaction',
    label: 'Click strength',
    description: 'Attraction force applied by clicks and taps.',
    defaultValue: 5.2,
    recommended: { min: 1, max: 10, step: 0.1 },
    runtime: { min: 0, max: 30 },
  },
  scrollStrength: {
    group: 'interaction',
    label: 'Scroll strength',
    description: 'Force transferred from page scrolling to the particle field.',
    defaultValue: 1.02,
    recommended: { min: 0, max: 3, step: 0.01 },
    runtime: { min: 0, max: 10 },
  },
});
